# Person Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
      - name: person-service
        image: person-service:v2  # Usando a imagem que você carregou no kind
        imagePullPolicy: Never         # Certifique-se de que o Kubernetes não vai tentar puxar a imagem da internet
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "sa"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""
