apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: person-service
  namespace: argocd
spec:
  description: Projeto para a aplicação person-service
  sourceRepos:
    - '*'
  destinations:
    - namespace: person-service-namespace
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
