name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite o acionamento manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout source code
      uses: actions/checkout@v2

    # Configurar o Java JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    # Executar o build da aplicação (Maven/Gradle)
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Fazer login no Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Construir a imagem Docker
    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/person-service:${{ github.sha }}

    # Push da imagem para o Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/person-service:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout do código do repositório
    - name: Checkout source code
      uses: actions/checkout@v2

    # Instalar o kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # Instalar o ArgoCD CLI
    - name: Install ArgoCD CLI
      run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/v2.4.11/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd

    # Fazer o port-forward para o ArgoCD server
    - name: Port-forward ArgoCD server
      run: |
        nohup kubectl port-forward svc/argocd-server -n argocd 8082:443 &

    # Fazer login no ArgoCD
    - name: Login to ArgoCD
      run: argocd login localhost:8082 --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

    # Atualizar a imagem da aplicação no ArgoCD
    - name: Update ArgoCD app
      run: |
        argocd app set person-service --repo https://github.com/${{ github.repository }} --revision ${{ github.sha }}
        argocd app sync person-service
